version: '3.8'
services:
  nest_graphql:
    container_name: nest_api_graphql
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/home/api
    depends_on:
      - database
      - redis
  database:
    container_name: nest_db_graphql
    image: 'postgres:13'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    
  redis: 
    container_name: redis
    
    image: 'bitnami/redis:latest'

    ports:
      - 6379:6379

    environment:
      - ALLOW_EMPTY_PASSWORD=yes

 